<?php

return [
    
    /*
    |---------------------------------------------------------------------------
    | Exceptions Codes
    |---------------------------------------------------------------------------
    |
    | This values determine the code of each exception. This codes are useful 
    | to identify the errors generated by your API. You can set your own codes
    | and add more fields and codes to `validation_fields` array. The `default`
    | code is from not managed exceptions.
    */
    'codes' => [
        'default' => 1,
        'authorization' => 12,
        'model_not_found' => 13,
        'validation' => 14,
        'validation_fields' => [
            'name' => 141,
            'email' => 142,
        ]
    ],

    /*
    |---------------------------------------------------------------------------
    | Default Http Code
    |---------------------------------------------------------------------------
    |
    | The http code value to not managed exceptions. Generally the code used is
    | 500 - Internal Server Error. 
    */
    'http_code' => 500,

];
