<?php

namespace SMartins\JsonHandler;

use Illuminate\Validation\ValidationException;
use SMartins\JsonHandler\Responses\Response;

trait ValidationHandler
{
    /**
     * Assign to response attribute the value to ValidationException.
     *
     * @param  ValidationException $exception
     */
    public function validationException(ValidationException $exception)
    {
        $this->response->setMessage('The given data failed to pass validation.');
        $this->response->setCode($this->getCode('validation'));
        $this->response->setErrors($this->formattedErrors($exception));
        $this->response->setHttpCode(422);
    }

    /**
     * Get formatted errors on standard code, field, message to each field with
     * error
     *
     * @param  ValidationException $exception
     * @return array
     */
    public function formattedErrors(ValidationException $exception)
    {
        return $this->formatErrorMessages($this->getTreatedMessages($exception));
    }

    /**
     * Get message based on exception type. If exception is generated by
     * $this->validate() from default Controller methods the exception has the
     * response object. If exception is generated by Validator::make() the
     * messages are getted different.
     *
     * @param  Exception $exception
     * @return array
     */
    public function getTreatedMessages($exception)
    {
        $messages = [];
        if ($exception->response) {
            $messages = $this->getMessagesFromJsonResponse($exception);
        } else {
            $messages = $this->getMessagesFromValidator($exception);
        }

        return $messages;
    }
    
    public function getMessagesFromJsonResponse($exception)
    {
        return $exception->response->original;
    }

    public function getMessagesFromValidator($exception)
    {
        return $exception->validator->messages()->messages();
    }

    public function formatErrorMessages($messages)
    {
        $errors = [];
        foreach ($messages as $field => $message) {
            $error = [
                'code' => config('json-exception-handler.codes.validation_fields.'.$field),
                'field' => $field,
                'message' => $message
            ];

            array_push($errors, $error);
        }

        return $errors;
    }
}
